---
# Docker Engine deployment

- include: remove-old.yml
  when: "{{ remove_old_docker_engine }}"

- include: install.yml

- include: ssl-certificates.yml
  when: '{{ ssl_certificates | length }} > 0'

# enable docker execution *without* sudo
- include: permissions.yml
  when: "{{ add_user_to_docker_group }}"