---
# Docker Engine deployment

# Docker-Engine CS or Public Domain Docker-Engine
- include_vars: "vars/docker-engine-{{ docker_engine_type | default('public') }}.yml"

- include: remove-old.yml
  when: "{{ remove_old_docker_engine }}"

- include: install.yml
- include: ssl-certificates.yml

# enable docker execution *without* sudo
- include: permissions.yml
  when: "{{ add_user_to_docker_group }}"